# vim: ft=yaml
---
driver:
  name: docker
  hostname: helm.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef_for_busser: false
  formula: postfix
  log_level: info
  state_top:
    base:
      "*":
        - postfix
  pillars:
    top.sls:
      base:
        "*":
          - postfix
    postfix.sls:
      server:
        ssl:
          enabled: false
  grains:
    noservices: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: server
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/server.sls
    driver:
      hostname: postfix.ci.local

  - name: relay
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/relay.sls

  - name: backupmx
    provisioner:
      pillars-from-files:
        postfix.sls: tests/pillar/backupmx.sls
